### PR TITLE
Add author field

### PR DESCRIPTION
**Pull request by szabgab**
See also: https://pydigger.com/docs/author

### CODE REVIEW

**Comment by unnown** [comment]
Please mark as invalid and spam, this is an obvious attempt to get a free t-shirt by 'contributing'(hacktoberfest)
This will also ban the user for trying to abuse the system by doing marginal effort

**Comment by szabgab** [comment]
Wow, someone decided to spam GitHub. Several of my PRs got this comment (but none of the PRs that my projects received). Disregard it. Use your own judgement. I've reported this abuse to GitHub.

**Comment by unnown** [comment]
You reported yourself? good idea tbh

**Comment by pabloBad** [comment]
I assume that any event of this type will have some sort of verification to prevent the marginal contribution from being rewarded.
I will rely on the good faith of @szabgab .

**Pull request merged**
